[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "/home/iceseer/Work/polkadot-sdk/target/release/polkadot"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9902
    validator = true
    command = "/home/iceseer/Work/kagome/build-ex/node/kagome"
    prometheus_prefix = "kagome"
    args = [ "-lruntime=debug", "-lparachain=trace", "--wasm-execution","Compiled","--unsafe-cached-wavm-runtime" ]

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 9903
    validator = true
    args = [ "-lruntime=debug,parachain=trace" ]

[[parachains]]
id = 100
add_to_genesis = true

  [parachains.collator]
  name = "collator01"
  command = "/home/iceseer/Work/polkadot-sdk/target/testnet/adder-collator"
  args = [ "-lruntime=debug,parachain=trace" ]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
